name: Release with commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get tag from commit message
        id: get_tag
        run: |
          TAG=$(echo "${{ github.event.head_commit.message }}" | grep -oE 'Release (([0-9]+([.][0-9]+)*-(alpha|beta|rc)[0-9]+))' | head -n1 | awk '{print $2}')
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ steps.get_tag.outputs.tag_name }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_ENV
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_ENV
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create release if tag does not exist
        if: steps.check_tag.outputs.exists == 'false'
        uses: ChanTsune/release-with-commit@v2.8.0
        id: create_release
        with:
          regexp: "Release ((\\d+([.]\\d+)*)-(alpha|beta|rc)\\d*)((\\s|\\S)*)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$5"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Ensure release exists for tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          files: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Chrome dist zip to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist-chrome.zip
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Firefox dist zip to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist-firefox.zip
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Edge dist zip to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist-edge.zip
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
