name: Release with commit

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v2.8.0
        with:
          regexp: "Release ((\\d+([.]\\d+)*)-(alpha|beta|rc)\\d*)((\\s|\\S)*)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$5"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}' # This token is provided by Actions, you do not need to create your own token

      # Add these steps after your existing release step
      - name: Upload Chrome dist zip to Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: dist-chrome.zip

      - name: Upload Firefox dist zip to Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: dist-firefox.zip

      - name: Upload Edge dist zip to Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: dist-edge.zip
